# Generated by Django 3.1.3 on 2020-12-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Uid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_field',
            field=models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('MEDICAL', 'MEDICAL'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
    ]
