# Generated by Django 3.1.3 on 2020-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20201216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classid',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
