# Generated by Django 3.1.3 on 2020-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20201218_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
