# Generated by Django 3.1.3 on 2020-12-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20201218_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
