# Generated by Django 3.1.3 on 2020-12-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_auto_20201218_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
