# Generated by Django 3.1.3 on 2020-12-18 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
