# Generated by Django 3.1.3 on 2020-12-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_auto_20201218_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='lass_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.classroom'),
        ),
    ]
