# Generated by Django 3.1.3 on 2020-12-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_auto_20201218_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField()),
                ('att_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.classroom')),
                ('attendees', models.ManyToManyField(to='Accounts.profile')),
            ],
        ),
    ]
