# Generated by Django 3.1.3 on 2021-01-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_auto_20210109_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posted_by',
        ),
    ]
