# Generated by Django 3.1.3 on 2021-01-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_auto_20210110_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
