# Generated by Django 3.1.3 on 2021-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='rem_members',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
