# Generated by Django 3.1.3 on 2020-12-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
